#!/bin/sh

(
photo-import $1
) |
zenity \
    --modal \
    --progress \
    --title="Photo importing" \
    --text="Importing photos into an album is in progress..." \
    --pulsate \
    --no-cancel \
    --auto-close

zenity \
    --notification \
    --text="Photo importing\nPhoto importing completed"

